# Connessione
CONNECTION_URL=jdbc:mysql://localhost:3306/brainbankdb

LOGIN_USER=bb_login
LOGIN_PASS=bb_login

STUDENT_USER=bb_student
STUDENT_PASS=bb_student

TUTOR_USER=bb_tutor
TUTOR_PASS=bb_tutor

ADMIN_USER=bb_admin
ADMIN_PASS=bb_admin

# SENDGRID
SENDGRID_API_KEY=your_sendgrid_api_key_here
SENDGRID_FROM_EMAIL=your_sender_email_here