# Connessione
CONNECTION_URL=jdbc:mysql://localhost:3306/brainbankdb

LOGIN_USER=bb_login
LOGIN_PASS=bb_login
?
STUDENT_USER=bb_student
STUDENT_PASS=bb_student

TUTOR_USER=bb_tutor
TUTOR_PASS=bb_tutor

ADMIN_USER=bb_admin
ADMIN_PASS=bb_admin

# SENDGRID
SENDGRID_API_KEY=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
SENDGRID_FROM_EMAIL=brainbankuni@gmail.com
